### ISSUE TITLE
[ISSUE] ORA-06550: line 1, column 6: PLS-00103: Encountered the symbol ";" when expecting one of the following

### ISSUE THREAD

**Issue by spyhunter88** [evolute-pt/dbtransfer#17]
Hi, 
I test with Oracle 11.2.0.1 and Java 1.8 and found hard to make it work. The one thing is it can not get current Schema with url jdbc.oracle:@hostname:1521/Schema. I have to change this code to select last part with only ORC.
But the next part is really hard to make it work. The issue show:
`ORA-06550: line 1, column 6:
PLS-00103: Encountered the symbol ";" when expecting one of the following:
  ( begin case declare exit for goto if loop mod null pragma
   raise return select update while with <an identifier>
   <a double-quoted delimited-identifier> <a bind variable> <<
   continue close current delete fetch lock insert open rollback
   savepoint set sql execute commit forall merge pipe purge

```
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:439)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:395)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:802)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:436)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:194)
at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1000)
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1307)
at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1882)
at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1847)
at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:301)
at pt.evolute.dbtransfer.db.jdbc.JDBCConnection.executeQuery(JDBCConnection.java:234)
at pt.evolute.dbtransfer.transfer.AsyncStatement.run(AsyncStatement.java:123)
```

`

Please fix it, I like this tool because it make me easy to transfer data scheduling without a big solution and hard to deploy.

**Comment by rcdsnts** [comment]
Hi!

it seems the error is due to the semi-colon in the "BEGIN**;**" statement ,
removing the trailing **;** from the _BEGIN_ , _COMMIT_  and _ROLLBACK_ statements should do the trick !

**Comment by spyhunter88** [comment]
I also try, and the error change to:
`
java.sql.SQLException: ORA-06550: line 1, column 5:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   ( begin case declare exit for goto if loop mod null pragma
   raise return select update while with <an identifier>
   <a double-quoted delimited-identifier> <a bind variable> <<
   continue close current delete fetch lock insert open rollback
   savepoint set sql execute commit forall merge pipe purge

```
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:439)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:395)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:802)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:436)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:194)
at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1000)
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1307)
at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1882)
at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1847)
at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:301)
at pt.evolute.dbtransfer.db.jdbc.JDBCConnection.executeQuery(JDBCConnection.java:234)
at pt.evolute.dbtransfer.transfer.AsyncStatement.run(AsyncStatement.java:123)
```

`

**Comment by rcdsnts** [comment]
... it would be just to easy ...

I do not have a proper setup to replicate this error by myself.

Based on the errors you reported and after a quick internet search it seems that the _BEGIN_ is not being perceived as a start of a transaction instead the statement parser thinks it is starting some other kind of statement block ...

As i said before i do not have a proper system to replicate the bug,
and it seems that by default oracle always start a transaction per session,
so **I think** we can comment out the transaction begin for oracle
can you just comment out the line number 123 in the file  AsyncStatement.java
`CONN.executeQuery( "BEGIN;" );`
becomes
`//CONN.executeQuery( "BEGIN;" );`

anyway it needs a proper testing and a deeper understanding how the oracle driver is dealing with the transactions,
if the suggested approach is a way to go, maybe the transaction management operations will need to be pushed to the Helper.java ... Different RDBMS different ways to manage transactions ( **start** )

**Comment by spyhunter88** [comment]
Yep, I get the following error:
`
EX in: import_log INSERT INTO import_log ( "id",
java.lang.NumberFormatException: For input string: "id"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at oracle.jdbc.driver.OraclePreparedStatement.setObjectCritical(OraclePreparedStatement.java:8289)
    at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:8034)
    at oracle.jdbc.driver.OraclePreparedStatement.setObject(OraclePreparedStatement.java:8575)
    at oracle.jdbc.driver.OraclePreparedStatementWrapper.setObject(OraclePreparedStatementWrapper.java:238)
    at pt.evolute.dbtransfer.db.helper.NullHelper.setPreparedValue(NullHelper.java:188)
    at pt.evolute.dbtransfer.transfer.AsyncStatement.addRowToStatement(AsyncStatement.java:242)
    at pt.evolute.dbtransfer.transfer.AsyncStatement.run(AsyncStatement.java:132)
`

I have tried to remove ';' character, comment `CONN.executeQuery("BEGIN");`, and from here I can not debug.
I have import_log with id, user, action, description, start_time and end_time column. 

I debug to function **setPreparedValue** in **NullHelper.java**, line `pStm.setObject(col + 1, outputValue( o ), translateType( type ) );`. I see the value of **o** is 'id' instead of  number.
I wonder why it put the header's name here?

**Comment by rcdsnts** [comment]
removing the **;** is not the way to go, I was mislead by the error message the second error you posted clear the doubts.

the _"id"_ error is more tricky it requires further investigation ...
did you change anything else
because it seems the fetch query is returning the column name instead of the value

some thing like 
`select id from table --> select 'id' from table ...`

**Comment by luiscamposflores** [comment]
Hello,
Thank you for the nice support Ricardo, I'm a bit busy right now but I'll try to reproduce the problem and commit the code without the ;.
Is it possible to post here the DDL of the table you are trying to transfer?

**Comment by spyhunter88** [comment]
Yes, I make a few changes to make it can get DB Schema from Oracle. Then I add a new TABLES_LIST properties to restrict which table to be transfer.
I think I will fork and commit to my repo so you can see the diff.

I also give you my DDL:
Source:

```
CREATE TABLE `import_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user` varchar(50) DEFAULT NULL,
  `action` varchar(50) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4252 DEFAULT CHARSET=utf8;
```

Destination:

```
CREATE TABLE "BCG"."IMPORT_LOG" (
"ID" NUMBER NULL ,
"USER" VARCHAR2(255 BYTE) NULL ,
"ACTION" VARCHAR2(255 BYTE) NULL ,
"DESCRIPTION" VARCHAR2(255 BYTE) NULL ,
"START_TIME" TIMESTAMP(7)  NULL ,
"END_TIME" TIMESTAMP(7)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
```

**Comment by spyhunter88** [comment]
I've updated my repo https://github.com/spyhunter88/dbtransfer, you can check it.
